namespace Infrastructure.Nutrition
{
  /// <summary>
  /// Maps short or ambiguous ingredient names to USDA FoodData Central–friendly search phrases.
  /// Keys are matched case-insensitively; whole-name match is tried first, then the first token of the name.
  /// </summary>
  internal static class IngredientSearchExpansionMap
  {
    internal static readonly Dictionary<string, string> Entries = new(StringComparer.OrdinalIgnoreCase)
    {
      // Poultry
      ["chicken"] = "chicken breast raw",
      ["chicken breast"] = "chicken breast raw",
      ["chicken thighs"] = "chicken thigh raw",
      ["chicken thigh"] = "chicken thigh raw",
      ["chicken wings"] = "chicken wing raw",
      ["chicken wing"] = "chicken wing raw",
      ["chicken drumstick"] = "chicken drumstick raw",
      ["chicken drumsticks"] = "chicken drumstick raw",
      ["chicken tender"] = "chicken tenderloin raw",
      ["chicken tenders"] = "chicken tenderloin raw",
      ["chicken liver"] = "chicken liver raw",
      ["turkey"] = "turkey breast raw",
      ["turkey breast"] = "turkey breast raw",
      ["ground turkey"] = "ground turkey raw",
      ["duck"] = "duck raw",
      ["goose"] = "goose raw",

      // Red meat
      ["beef"] = "ground beef raw",
      ["ground beef"] = "ground beef raw",
      ["steak"] = "beef steak raw",
      ["sirloin"] = "beef sirloin raw",
      ["ribeye"] = "beef ribeye raw",
      ["brisket"] = "beef brisket raw",
      ["stew beef"] = "beef stew meat raw",
      ["beef chuck"] = "beef chuck raw",
      ["veal"] = "veal raw",
      ["lamb"] = "lamb leg raw",
      ["lamb chop"] = "lamb chop raw",
      ["lamb chops"] = "lamb chop raw",
      ["pork"] = "pork loin raw",
      ["pork chop"] = "pork chop raw",
      ["pork chops"] = "pork chop raw",
      ["pork tenderloin"] = "pork tenderloin raw",
      ["pork shoulder"] = "pork shoulder raw",
      ["bacon"] = "bacon raw",
      ["ham"] = "ham sliced",
      ["sausage"] = "pork sausage raw",
      ["italian sausage"] = "italian sausage raw",

      // Fish & shellfish
      ["salmon"] = "salmon raw",
      ["tuna"] = "tuna raw",
      ["cod"] = "cod raw",
      ["tilapia"] = "tilapia raw",
      ["halibut"] = "halibut raw",
      ["trout"] = "trout raw",
      ["mackerel"] = "mackerel raw",
      ["sardines"] = "sardines canned in oil",
      ["shrimp"] = "shrimp raw",
      ["prawns"] = "shrimp raw",
      ["crab"] = "crab meat raw",
      ["lobster"] = "lobster raw",
      ["scallops"] = "scallop raw",
      ["scallop"] = "scallop raw",
      ["mussels"] = "mussel raw",
      ["clam"] = "clam raw",
      ["clams"] = "clam raw",

      // Eggs & plant protein
      ["egg"] = "egg whole raw",
      ["eggs"] = "egg whole raw",
      ["egg white"] = "egg white raw",
      ["egg whites"] = "egg white raw",
      ["egg yolk"] = "egg yolk raw",
      ["tofu"] = "tofu firm raw",
      ["tempeh"] = "tempeh raw",

      // Dairy
      ["milk"] = "whole milk",
      ["skim milk"] = "milk skim",
      ["2% milk"] = "milk reduced fat 2 percent",
      ["buttermilk"] = "buttermilk cultured",
      ["cream"] = "cream heavy whipping",
      ["heavy cream"] = "cream heavy whipping",
      ["whipping cream"] = "cream heavy whipping",
      ["half and half"] = "cream half and half",
      ["sour cream"] = "sour cream cultured",
      ["yogurt"] = "yogurt plain whole milk",
      ["greek yogurt"] = "yogurt greek plain whole milk",
      ["butter"] = "butter unsalted",
      ["margarine"] = "margarine stick",
      ["cream cheese"] = "cream cheese",
      ["cheddar"] = "cheddar cheese",
      ["mozzarella"] = "mozzarella cheese part skim",
      ["parmesan"] = "parmesan cheese grated",
      ["feta"] = "feta cheese",
      ["ricotta"] = "ricotta cheese whole milk",
      ["swiss cheese"] = "swiss cheese",
      ["provolone"] = "provolone cheese",
      ["goat cheese"] = "goat cheese soft",
      ["blue cheese"] = "blue cheese",

      // Fats & oils
      ["oil"] = "vegetable oil",
      ["vegetable oil"] = "vegetable oil",
      ["olive oil"] = "olive oil extra virgin",
      ["canola oil"] = "canola oil",
      ["coconut oil"] = "coconut oil",
      ["sesame oil"] = "sesame oil",
      ["shortening"] = "shortening vegetable",

      // Sweeteners
      ["sugar"] = "sugar granulated",
      ["brown sugar"] = "sugar brown packed",
      ["powdered sugar"] = "sugar powdered",
      ["confectioners sugar"] = "sugar powdered",
      ["honey"] = "honey",
      ["maple syrup"] = "maple syrup",
      ["molasses"] = "molasses",
      ["agave"] = "agave syrup",

      // Flours & grains
      ["flour"] = "all purpose flour",
      ["all purpose flour"] = "all purpose flour",
      ["bread flour"] = "wheat flour bread",
      ["whole wheat flour"] = "whole wheat flour",
      ["almond flour"] = "almond flour",
      ["cornmeal"] = "cornmeal yellow dry",
      ["corn starch"] = "corn starch",
      ["cornstarch"] = "corn starch",
      ["rice"] = "white rice uncooked",
      ["white rice"] = "white rice uncooked",
      ["brown rice"] = "brown rice uncooked",
      ["basmati rice"] = "basmati rice uncooked",
      ["jasmine rice"] = "jasmine rice uncooked",
      ["wild rice"] = "wild rice uncooked",
      ["oats"] = "oats rolled old fashioned dry",
      ["oatmeal"] = "oats rolled old fashioned dry",
      ["quinoa"] = "quinoa uncooked",
      ["couscous"] = "couscous dry",
      ["bulgur"] = "bulgur dry",
      ["barley"] = "barley pearled dry",
      ["farro"] = "farro dry",
      ["polenta"] = "cornmeal yellow dry",

      // Pasta & noodles
      ["pasta"] = "spaghetti dry",
      ["spaghetti"] = "spaghetti dry",
      ["penne"] = "pasta dry",
      ["macaroni"] = "macaroni dry",
      ["lasagna noodles"] = "lasagna noodles dry",
      ["noodles"] = "egg noodles dry",
      ["ramen"] = "ramen noodles dry",

      // Legumes
      ["lentils"] = "lentils dry",
      ["lentil"] = "lentils dry",
      ["chickpeas"] = "chickpeas dry",
      ["garbanzo beans"] = "chickpeas dry",
      ["black beans"] = "black beans dry",
      ["kidney beans"] = "kidney beans dry",
      ["pinto beans"] = "pinto beans dry",
      ["navy beans"] = "navy beans dry",
      ["white beans"] = "navy beans dry",
      ["cannellini beans"] = "white beans dry",
      ["split peas"] = "split peas dry",

      // Nuts & seeds
      ["almonds"] = "almonds raw",
      ["almond"] = "almonds raw",
      ["walnuts"] = "walnuts english raw",
      ["pecans"] = "pecans raw",
      ["peanuts"] = "peanuts raw",
      ["cashews"] = "cashews raw",
      ["pistachios"] = "pistachio nuts raw",
      ["hazelnuts"] = "hazelnuts raw",
      ["macadamia"] = "macadamia nuts raw",
      ["pine nuts"] = "pine nuts raw",
      ["chia seeds"] = "chia seeds dried",
      ["flaxseed"] = "flaxseed ground",
      ["flax seeds"] = "flaxseed ground",
      ["sesame seeds"] = "sesame seeds whole dried",
      ["sunflower seeds"] = "sunflower seed kernels dry roasted",
      ["pumpkin seeds"] = "pumpkin seeds raw",

      // Baking
      ["baking powder"] = "baking powder double acting",
      ["baking soda"] = "baking soda",
      ["yeast"] = "yeast active dry",
      ["active dry yeast"] = "yeast active dry",
      ["instant yeast"] = "yeast active dry",
      ["cocoa powder"] = "cocoa powder unsweetened",
      ["chocolate chips"] = "chocolate chips semisweet",
      ["vanilla"] = "vanilla extract",
      ["vanilla extract"] = "vanilla extract",

      // Produce (common short names)
      ["onion"] = "onions raw",
      ["onions"] = "onions raw",
      ["shallot"] = "shallots raw",
      ["garlic"] = "garlic raw",
      ["ginger"] = "ginger root raw",
      ["potato"] = "potatoes russet raw",
      ["potatoes"] = "potatoes russet raw",
      ["sweet potato"] = "sweet potato raw",
      ["sweet potatoes"] = "sweet potato raw",
      ["carrot"] = "carrots raw",
      ["carrots"] = "carrots raw",
      ["celery"] = "celery raw",
      ["tomato"] = "tomatoes raw",
      ["tomatoes"] = "tomatoes raw",
      ["bell pepper"] = "sweet red pepper raw",
      ["green pepper"] = "sweet green pepper raw",
      ["red pepper"] = "sweet red pepper raw",
      ["jalapeno"] = "peppers jalapeno raw",
      ["spinach"] = "spinach raw",
      ["kale"] = "kale raw",
      ["lettuce"] = "lettuce iceberg raw",
      ["cabbage"] = "cabbage raw",
      ["broccoli"] = "broccoli raw",
      ["cauliflower"] = "cauliflower raw",
      ["zucchini"] = "summer squash zucchini raw",
      ["squash"] = "winter squash raw",
      ["mushroom"] = "mushrooms white button raw",
      ["mushrooms"] = "mushrooms white button raw",
      ["cucumber"] = "cucumber raw with peel",
      ["avocado"] = "avocado hass raw",
      ["lemon"] = "lemon raw",
      ["lime"] = "lime raw",
      ["orange"] = "orange raw",
      ["apple"] = "apple raw with skin",
      ["apples"] = "apple raw with skin",
      ["banana"] = "banana raw",
      ["bananas"] = "banana raw",
      ["strawberry"] = "strawberries raw",
      ["strawberries"] = "strawberries raw",
      ["blueberry"] = "blueberries raw",
      ["blueberries"] = "blueberries raw",
      ["raspberry"] = "raspberries raw",
      ["grape"] = "grapes red or green raw",
      ["grapes"] = "grapes red or green raw",
      ["raisins"] = "raisins seedless",
      ["coconut"] = "coconut meat raw",
      ["pineapple"] = "pineapple raw",

      // Herbs & spices (ground/dried where common in recipes)
      ["salt"] = "salt table",
      ["kosher salt"] = "salt kosher",
      ["sea salt"] = "salt sea",
      ["black pepper"] = "black pepper ground",
      ["cinnamon"] = "cinnamon ground",
      ["nutmeg"] = "nutmeg ground",
      ["cloves"] = "cloves ground",
      ["cumin"] = "cumin ground",
      ["coriander"] = "coriander seed ground",
      ["paprika"] = "paprika",
      ["smoked paprika"] = "paprika",
      ["cayenne"] = "red pepper cayenne",
      ["chili powder"] = "chili powder",
      ["curry powder"] = "curry powder",
      ["turmeric"] = "turmeric ground",
      ["oregano"] = "oregano dried",
      ["basil"] = "basil dried",
      ["thyme"] = "thyme dried",
      ["rosemary"] = "rosemary dried",
      ["sage"] = "sage ground",
      ["bay leaf"] = "bay leaf dried",
      ["bay leaves"] = "bay leaf dried",
      ["parsley"] = "parsley fresh",
      ["cilantro"] = "coriander cilantro raw",
      ["dill"] = "dill weed dried",
      ["mint"] = "spearmint dried",

      // Liquids & condiments
      ["water"] = "water tap",
      ["broth"] = "chicken broth ready to serve",
      ["chicken broth"] = "chicken broth ready to serve",
      ["beef broth"] = "beef broth ready to serve",
      ["vegetable broth"] = "vegetable broth ready to serve",
      ["stock"] = "chicken stock ready to serve",
      ["wine"] = "wine table red",
      ["red wine"] = "wine table red",
      ["white wine"] = "wine table white",
      ["beer"] = "beer regular",
      ["vinegar"] = "vinegar distilled",
      ["apple cider vinegar"] = "vinegar cider",
      ["balsamic vinegar"] = "vinegar balsamic",
      ["rice vinegar"] = "vinegar rice",
      ["soy sauce"] = "soy sauce",
      ["worcestershire"] = "worcestershire sauce",
      ["hot sauce"] = "hot sauce",
      ["ketchup"] = "catsup",
      ["mustard"] = "mustard prepared yellow",
      ["mayonnaise"] = "mayonnaise regular",
      ["mayo"] = "mayonnaise regular",
      ["bbq sauce"] = "barbecue sauce",
      ["barbecue sauce"] = "barbecue sauce",
      ["peanut butter"] = "peanut butter smooth",
      ["tahini"] = "sesame butter tahini",
      ["miso"] = "miso paste",

      // Other common pantry
      ["bread"] = "bread white",
      ["breadcrumbs"] = "breadcrumbs dry",
      ["panko"] = "breadcrumbs panko",
      ["tortilla"] = "tortilla flour",
      ["tortillas"] = "tortilla flour",
      ["corn tortilla"] = "tortilla corn",
    };
  }
}
